title: Jinwoo's Portfolio
author: Jinwoo
markdown: kramdown
plugins:
  - jekyll-seo-tag

collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
